---
- name: install fs utilities
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - cifs-utils
    - samba-client
    - samba-common

- name: get tomcat uid
  shell: id -u tomcat | tr -d '\n'
  register: tomcat_uid

- name: get tomcat gid
  shell: id -g tomcat | tr -d '\n'
  register: tomcat_gid

- name: write mount configuration
  become: yes
  lineinfile:
    create: yes
    dest: /etc/fstab
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0600
    line: "{{ netapp_fedora_fs['server'] }} {{ netapp_fedora_fs['mount_point'] }} {{ netapp_fedora_fs['fs_type'] }} {{ netapp_fedora_fs['mount_opts'] }},uid={{ tomcat_uid.stdout }},gid={{ tomcat_gid.stdout }},user={{ netapp_fedora_fs['user'] }},password=\"{{ netapp_fedora_password }}\""

# - name: check mount point
#   stat:
#     path: "{{ netapp_fedora_fs['mount_point'] }}"
#   register: mnt

# - name: create mount point
#   become: yes
#   file:
#     path: "{{ netapp_fedora_fs['mount_point'] }}"
#     state: directory
#     owner: "{{ ansible_ssh_user }}"
#     group: "{{ ansible_ssh_user }}"
#   when: mnt.stat.isdir is defined and mnt.stat.isdir

- name: mount new volumes
  become: yes
  command: mount -a
