---
- name: update all yum packages
  become: yes
  yum:
    name: "*"
    state: latest
    update_cache: yes

- name: install Tomcat
  become: yes
  yum:
    name: "{{ item }}"
  with_items:
    - java-1.8.0-openjdk
    - tomcat
    - tomcat-admin-webapps
    - tomcat-webapps

- name: start Tomcat
  become: yes
  systemd:
    daemon_reload: yes
    name: tomcat
    enabled: yes
    state: started

- name: create Tomcat config and Java options
  become: yes
  template: src=tomcat.j2 dest=/etc/tomcat/tomcat.conf backup=yes

- name: add log rotation for catalina.out
  copy:
    src: logrotate-tomcat.conf
    dest: /etc/logrotate.d/tomcat7
