---
- include: install.yml
- include: fstab.yml
- include: fedora.yml
- include: marmotta.yml
- include: tomcat_firewall.yml

- name: restart Tomcat
  become: yes
  systemd:
    name: tomcat
    enabled: yes
    state: restarted
