---
- name: Ensure {{ install_path }} is writeable
  file:
    path: "{{ install_path }}"
    state: directory
    mode: 0777

- name: download Marmotta
  get_url:
    url: http://mirror.cc.columbia.edu/pub/software/apache/marmotta/{{ marmotta_ver }}/apache-marmotta-{{ marmotta_ver }}-webapp.tar.gz
    checksum: sha256:{{ marmotta_256 }}
    dest: "{{ install_path }}/apache-marmotta-{{ marmotta_ver }}-webapp.tar.gz"

- name: unpack Marmotta
  unarchive:
    src: "{{ install_path }}/apache-marmotta-{{ marmotta_ver }}-webapp.tar.gz"
    dest: "{{ install_path }}/"
    creates: "{{ install_path }}/apache-marmotta-{{ marmotta_ver }}/marmotta.war"

- name: install Marmotta
  copy:
    dest: "{{ tomcat }}/webapps/marmotta.war"
    group: tomcat
    owner: tomcat
    remote_src: yes
    src: "{{ install_path }}/apache-marmotta-{{ marmotta_ver }}/marmotta.war"

- name: create {{ marmotta_home }}
  file:
    group: tomcat
    owner: tomcat
    path: "{{ marmotta_home }}"
    state: directory

- name: set Marmotta system config properties
  template:
    src: system-config.properties.j2
    dest: "{{ marmotta_home }}/system-config.properties"
    owner: tomcat
    group: tomcat
    mode: 0600

- name: restart Tomcat
  service:
    name: tomcat
    enabled: yes
    state: restarted
