---
- name: Ensure {{ install_path }} is writeable
  become: yes
  file:
    path: "{{ install_path }}"
    state: directory
    mode: 0777

- name: download Marmotta
  get_url:
    url: http://mirror.cc.columbia.edu/pub/software/apache/marmotta/{{ marmotta_ver }}/apache-marmotta-{{ marmotta_ver }}-webapp.tar.gz
    checksum: sha256:{{ marmotta_256 }}
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    dest: "{{ install_path }}/apache-marmotta-{{ marmotta_ver }}-webapp.tar.gz"

- name: unpack Marmotta
  unarchive:
    src: "{{ install_path }}/apache-marmotta-{{ marmotta_ver }}-webapp.tar.gz"
    dest: "{{ install_path }}/"
    creates: "{{ install_path }}/apache-marmotta-{{ marmotta_ver }}/marmotta.war"
    copy: no

- name: install Marmotta
  become: yes
  command: cp {{ install_path }}/apache-marmotta-{{ marmotta_ver }}/marmotta.war {{ tomcat }}/webapps/marmotta.war
  args:
    creates: "{{ tomcat }}/webapps/marmotta.war"

- name: set ownership on marmotta.war
  become: yes
  file:
    path: "{{ tomcat }}/webapps/marmotta.war"
    owner: tomcat
    group: tomcat

- name: create {{ marmotta_home }}
  become: yes
  file:
    group: tomcat
    owner: tomcat
    path: "{{ marmotta_home }}"
    state: directory

- name: set Marmotta system config properties
  become: yes
  template:
    src: system-config.properties.j2
    dest: "{{ marmotta_home }}/system-config.properties"
    owner: tomcat
    group: tomcat
    backup: no
    mode: 0600

- name: restart Tomcat
  become: yes
  service:
    name: tomcat
    enabled: yes
    state: restarted

- name: wait for Marmotta to install libs
  wait_for:
    path: "{{ tomcat }}/webapps/marmotta/WEB-INF/lib/log4j-over-slf4j-1.7.7.jar"

# Currently Marmotta tries to install a
# logging library that conflicts with Solr's, so for now we're just
# removing that library.
# Check - is the library installed before Marmotta runs?
# If not, restart tomcat after installing Marmotta, then remove
# the library, then restart Tomcat again.

- name: remove log4j-over-slf4j.jar
  become: yes
  file: path={{ item }} state=absent
  with_items:
    - "{{ tomcat }}/webapps/marmotta/WEB-INF/lib/log4j-over-slf4j-1.7.7.jar"

  # Otherwise subsequent runs will hang on the "wait_for" above
- name: touch removed library
  become: yes
  file:
    path: "{{ tomcat }}/webapps/marmotta/WEB-INF/lib/log4j-over-slf4j-1.7.7.jar"
    state: touch

- name: restart tomcat
  become: yes
  service:
    name: tomcat
    enabled: yes
    state: restarted
