---
- name: start firewalld
  systemd:
    name: firewalld
    state: started
    enabled: yes

  # https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Security_Guide/sec-Using_Firewalls.html
- name: add Tomcat to firewalld allowed ports
  command: firewall-cmd --add-port=8080/tcp --permanent --zone=internal

- name: reload firewalld
  command: firewall-cmd --reload
