---
- name: install Tomcat and prerequisites
  become: yes
  yum: name={{ item }} state=present
  with_items:
    - tomcat
    - tomcat-admin-webapps
    - tomcat-webapps

- name: set Tomcat to restart on reboot
  become: yes
  service: name=tomcat enabled=yes
