---
- name: install Tomcat and prerequisites
  become: yes
  yum: name={{ item }} state=present
  with_items:
    - tomcat
    - tomcat-admin-webapps
    - tomcat-webapps

- name: start Tomcat
  become: yes
  systemd:
    daemon_reload: yes
    name: tomcat
    enabled: yes
    state: started
